### ISSUE TITLE
Automatisk versjonering av kildekoden

### ISSUE THREAD

**Issue by thomiz** [xivind/velo-supervisor-2000#85]
Noen ideer [her](https://stackoverflow.com/questions/37814286/how-to-manage-the-version-number-in-git) og [her](https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions)

**Comment by xivind** [comment]
Løses i sammenheng med #83

**Comment by xivind** [comment]
Takk for gode tips her @thomiz 👍 Jeg gikk for alternativet med å bruke tags. Så har jeg et script som leser tags og beregner versjonsnr når containeren bygges. Lar den stå til review en stund, så vi ser det funker etter hvert som commitene og taggene ruller fremover.
![Image](https://github.com/user-attachments/assets/1796da12-68df-4db1-a094-82b5833b25b9)
